' Copyright 2002-2026 Luc Maisonobe
' Licensed to CS GROUP (CS) under one or more
' contributor license agreements.  See the NOTICE file distributed with
' this work for additional information regarding copyright ownership.
' CS licenses this file to You under the Apache License, Version 2.0
' (the "License"); you may not use this file except in compliance with
' the License.  You may obtain a copy of the License at
'
'   http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml

  skinparam svek                  true
  skinparam ClassBackgroundColor  #F3EFEB/CCC9C5
  skinparam ClassArrowColor       #691616
  skinparam ClassBorderColor      #691616
  skinparam NoteBackgroundColor   #F3EFEB
  skinparam NoteBorderColor       #691616
    skinparam ClassFontSize         11
  skinparam PackageFontSize       12
  skinparam linetype              ortho

  package org.orekit.propagation #ECEBD8 {

    interface Propagator {
      +MatricesHarvester setupMatricesComputation(stmName, initialSTM, initialJacobianColumns)
      +SpacecraftState propagate()
    }

    interface MatricesHarvester {
      +setReferenceState(reference)
      +RealMatrix getStateTransitionMatrix(state)
      +RealMatrix getParametersJacobian(state)
      +RealMatrix getInitialStateJacobianVsBuilderParameters()
      +List<String> getJacobiansColumnsNames()
      +OrbitType getOrbitType()
      +PositionAngleType getPositionAngleType()
    }
    note left
    the orbit type can be anything
    (Keplerian, Circular, Equinoctial, Cartesian)
    end note

    class SpacecraftState {
      +double[] getAdditionalState(name)
    }
    note top
      contains the partial derivatives as a flatten array
    end note

    abstract AbstractMatricesHarvester

    package semianalytical #DDEBD8 {
      package dsst #CBDBC8 {
        class DSSTHarvester
      }
    }

    package numerical #DDEBD8 {
      class NumericalPropagationHarvester
    }

    package analytical #DDEBD8 {

      abstract AbstractAnalyticalMatricesHarvester {
        +getGradientConverter()
      }

      class BrouwerLyddaneHarvester
      class EcksteinHechlerHarvester
      class KeplerianHarvester

      package tle #CBDBC8 {
        class TLEHarvester
      }

      package gnss #CBDBC8 {
        class GnssHarvester
      }

    }

    Propagator                          --> MatricesHarvester: create
    Propagator                          --> SpacecraftState: create
    MatricesHarvester                   --> SpacecraftState
    MatricesHarvester                   <|.. AbstractMatricesHarvester
    AbstractMatricesHarvester           <|-- NumericalPropagationHarvester
    AbstractMatricesHarvester           <|-- DSSTHarvester
    AbstractMatricesHarvester           <|-- AbstractAnalyticalMatricesHarvester
    AbstractAnalyticalMatricesHarvester <|-- BrouwerLyddaneHarvester
    AbstractAnalyticalMatricesHarvester <|-- EcksteinHechlerHarvester
    AbstractAnalyticalMatricesHarvester <|-- KeplerianHarvester
    AbstractAnalyticalMatricesHarvester <|-- TLEHarvester
    AbstractAnalyticalMatricesHarvester <|-- GnssHarvester

  }

@enduml
