' Copyright 2022-2026 Thales Alenia Space
' Licensed to CS GROUP (CS) under one or more
' contributor license agreements.  See the NOTICE file distributed with
' this work for additional information regarding copyright ownership.
' CS licenses this file to You under the Apache License, Version 2.0
' (the "License"); you may not use this file except in compliance with
' the License.  You may obtain a copy of the License at
'
'   http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml

  skinparam svek                  true
  skinparam ClassBackgroundColor  #F3EFEB/CCC9C5
  skinparam ClassArrowColor       #691616
  skinparam ClassBorderColor      #691616
  skinparam NoteBackgroundColor   #F3EFEB
  skinparam NoteBorderColor       #691616
  skinparam NoteFontColor         #691616
  skinparam ClassFontSize         11
  skinparam PackageFontSize       12
  skinparam linetype              ortho

  package "org.orekit" as clocks #ECEBD8 {

    package utils #DDEBD8 {
      class ParameterDriver
    }

    package time #DDEBD8 {

      class AbsoluteDate

      class "FieldAbsoluteDate<T>" as FieldAbsoluteDate_T

      class TimeSpanMap

      interface TimeStamped {
        +AbsoluteDate getDate()
      }

      interface "FieldTimeStamped<T>" as FieldTimeStamped_T {
        +AbsoluteDate getDate()
      }

      abstract class "AbstractFieldTimeInterpolator<T>" as AbstractFieldTimeInterpolator_T {
        +interpolate()
      }

      abstract class AbstractTimeInterpolator {
        +interpolate()
      }

      AbsoluteDate <-- TimeStamped
      FieldAbsoluteDate_T <-- FieldTimeStamped_T

      package "clocks" as clocks #CBDBC8 {

        class ClockOffset {
          +double getOffset()
          +double getRate()
          +double getAcceleration()
          +ClockOffset add()
          +ClockOffset subtract()
        }

        class "FieldClockOffset<T>" as FieldClockOffset_T {
          +double getOffset()
          +double getRate()
          +double getAcceleration()
          +FieldClockOffset_T add()
          +FieldClockOffset_T subtract()
        }

        interface ClockModel {
          +AbsoluteDate getValidityStart()
          +AbsoluteDate getValidityEnd()
          +ClockOffset getOffset(AbsoluteDate)
          +FieldClockOffset<T> getOffset(FieldAbsoluteDate<T>)
        }

        class SampledClockModel {
          -nbInterpolationPoints
        }

        class ConstantClockModel {
          -offset
        }
        class PerfectClockModel
        note bottom
          offset is always zero
        end note

        class QuadraticClockModel
        class AggregatedClockModel
        abstract class AbstractCombinedClocksPair
        class ClocksSum
        class ClocksDifference
        class ClockOffsetHermiteInterpolator
        class "FieldClockOffsetHermiteInterpolator<T>" as FieldClockOffsetHermiteInterpolator_T
        class "QuadraticFieldClockModel<T>" as QuadraticFieldClockModel_T
        note right
          not really an implementation of ClockModel
          it just uses field versions of a₀, a₁, a₂
        end note

        TimeStamped        <|.. ClockOffset
        FieldTimeStamped_T <|.. FieldClockOffset_T
        QuadraticClockModel *-right-> ParameterDriver : "a₀, a₁, a₂"
        ClockOffset        <-- ClockModel : generate
        FieldClockOffset_T <-- ClockModel : generate
        ClockOffset    "*" <--* SampledClockModel : sample
        AggregatedClockModel *--> TimeSpanMap : models map
        ClockModel     "2" <--* AbstractCombinedClocksPair

        QuadraticFieldClockModel_T --> FieldClockOffset_T : generate

        ClockModel         <|.. SampledClockModel
        ClockModel         <|.. ConstantClockModel
        ClockModel         <|.. QuadraticClockModel
        ClockModel         <|.. AggregatedClockModel
        ClockModel         <|.. AbstractCombinedClocksPair
        ConstantClockModel <|-- PerfectClockModel
        AbstractCombinedClocksPair <|-- ClocksSum
        AbstractCombinedClocksPair <|-- ClocksDifference
        AbstractTimeInterpolator <|-- ClockOffsetHermiteInterpolator
        ClockOffsetHermiteInterpolator --> ClockOffset : interpolate
        AbstractFieldTimeInterpolator_T <|-left- FieldClockOffsetHermiteInterpolator_T
        FieldClockOffset_T        <-- FieldClockOffsetHermiteInterpolator_T : interpolate

      }

    }

 }

@enduml
