' Copyright 2002-2016 CS Systèmes d'Information
' Licensed to CS Systèmes d'Information (CS) under one or more
' contributor license agreements.  See the NOTICE file distributed with
' this work for additional information regarding copyright ownership.
' CS licenses this file to You under the Apache License, Version 2.0
' (the "License"); you may not use this file except in compliance with
' the License.  You may obtain a copy of the License at
'
'   http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml

  skinparam svek                  true
  skinparam ClassBackgroundColor  #F3EFEB/CCC9C5
  skinparam ClassArrowColor       #691616
  skinparam ClassBorderColor      #691616
  skinparam NoteBackgroundColor   #F3EFEB
  skinparam NoteBorderColor       #691616
  skinparam NoteFontColor         #691616
  skinparam ClassFontSize         11
  skinparam PackageFontSize       12

  package org.orekit #ECEBD8 {

    package frames #DDEBD8 {
      class Frame
    }

    package time #DDEBD8 {
      interface TimeStamped
      interface "TimeShiftable<T>" as TimeShiftable_T_
      interface "TimeInterpolable<T>" as TimeInterpolable_T_
    }

    package attitude #DDEBD8 {

      class Attitude {
	    +Vector3D estimateSpin
    	+Attitude withReferenceFrame
    	+Frame getReferenceFrame
        +Rotation getRotation
	    +Vector3D getSpin
      }

      class AttitudesSequence {
        +void resetActiveProvider
        +void registerSwitchEvents
        +void addSwitchingCondition
      }

      interface AttitudeProvider {
        + Attitude getAttitude(PVCoordinatesProvider pvProv, AbsoluteDate date, Frame frame)
      }

      class FixedRate {
        +Attitude getReferenceAttitude()
      }

      interface AttitudeProviderModifier {
        +AttitudeProvider getUnderlyingAttitudeProvider()
      }

      class SpinStabilized {
        +AttitudeProvider getNonRotatingLaw()
      }

      abstract class GroundPointing {
        #Vector3D getTargetPoint
        #PVCoordinates getTargetPV
      }

      abstract class GroundPointingWrapper {
        +Attitude getBaseState
        +Rotation getCompensation
      }

      Frame            <-up- "1" Attitude 
      Attitude         <-up- AttitudeProvider : create
      TimeStamped      <|.. Attitude
      TimeShiftable_T_ <|.. Attitude
      TimeInterpolable_T_ <|.. Attitude
      AttitudeProvider             <|-- FixedRate
      AttitudeProvider <|-- AttitudeProviderModifier
      AttitudesSequence ..|> AttitudeProvider
      AttitudesSequence "*" o--> AttitudeProvider
      AttitudeProvider <--* "1" LofOffsetPointing 
      AttitudeProvider <|.. GroundPointing
      GroundPointing   <|-- GroundPointingWrapper
      LofOffsetPointing            --|> GroundPointing

      AttitudeProviderModifier     <|-- SpinStabilized
      AttitudeProviderModifier     <|-- GroundPointingWrapper
      GroundPointing               <|-- BodyCenterPointing
      GroundPointing               <|-- NadirPointing
      GroundPointing               <|-- TargetPointing
      GroundPointingWrapper    "1" *--> GroundPointing
      GroundPointingWrapper        <|-- YawCompensation
      GroundPointingWrapper        <|-- YawSteering
      AttitudeProvider             <|-- CelestialBodyPointed
      AttitudeProvider             <|-- InertialProvider
      AttitudeProvider             <|-- LofOffset
      AttitudeProvider             <|-- TabulatedProvider

    }

  }

@enduml
