' Copyright 2002-2021 CS GROUP
' Licensed to CS GROUP (CS) under one or more
' contributor license agreements.  See the NOTICE file distributed with
' this work for additional information regarding copyright ownership.
' CS licenses this file to You under the Apache License, Version 2.0
' (the "License"); you may not use this file except in compliance with
' the License.  You may obtain a copy of the License at
'
'   http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml

  skinparam svek                  true
  skinparam ClassBackgroundColor  #F3EFEB/CCC9C5
  skinparam ClassArrowColor       #691616
  skinparam ClassBorderColor      #691616
  skinparam NoteBackgroundColor   #F3EFEB
  skinparam NoteBorderColor       #691616
  skinparam NoteFontColor         #691616
  skinparam ClassFontSize         11
  skinparam PackageFontSize       12
  skinparam linetype              ortho

  package org.orekit.files #ECEBD8 {

    package general #DDEBD8 {
        interface EphemerisFile {
          +getSatellites()
        }

        interface EphemerisFile.SatelliteEphemeris {
          +getId()
          +getMu()
          +getSegments()
          +getStart()
          +getStop()
          +getPropagator()
        }

        interface EphemerisFile.EphemerisSegment {
          +getMu()
          +getFrame()
          +getInertialFrame()
          +getInterpolationSamples()
          +getAvailableDerivatives()
          +getCoordinates()
          +getStart()
          +getStop()
          +getPropagator()
        }

        interface EphemerisFileWriter
        class OrekitEphemerisFile

    }

    package ccsds #DDEBD8 {

      package utils #CBDBC8 {

        enum FileFormat {
          +KVN
          +XML
        }

        package generation #CCCCC7 {
          class KvnGenerator
          class XmlGenerator
          interface Generator {
            +FileFormat getFileFormat()
          }
        }

      }

      package ndm.odm #CBDBC8 {

        package oem #CCCCC7 {
          class OemWriter
          class OemFile
        }

        package opm #CCCCC7 {
          class OpmWriter
          class OpmFile
        }

      }
      note bottom
        only OEM and OPM are shown here,
        similar constructions exist
        for other messages types:
        OMM, OCM, AEM, APM, TDM...
      end note

    }

  }

  Generator <|.. KvnGenerator
  Generator <|.. XmlGenerator
  FileFormat <-- Generator
  EphemerisFile *--> EphemerisFile.SatelliteEphemeris
  EphemerisFile.SatelliteEphemeris o--> EphemerisFile.EphemerisSegment
  OrekitEphemerisFile ..|> EphemerisFile
  EphemerisFileWriter --> EphemerisFile
  EphemerisFileWriter <|.. OemWriter
  EphemerisFile       <|.. OemFile
  OemWriter --> OemFile
  OemWriter --> Generator
  OpmWriter --> OemFile
  OpmWriter --> Generator

@enduml
