' Copyright 2002-2016 CS Systèmes d'Information
' Licensed to CS Systèmes d'Information (CS) under one or more
' contributor license agreements.  See the NOTICE file distributed with
' this work for additional information regarding copyright ownership.
' CS licenses this file to You under the Apache License, Version 2.0
' (the "License"); you may not use this file except in compliance with
' the License.  You may obtain a copy of the License at
'
'   http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.
 
@startuml

  skinparam svek                                true
  skinparam NoteBackgroundColor                 #F3EFEB
  skinparam NoteBorderColor                     #691616
  skinparam NoteFontColor                       #691616
  skinparam SequenceActorBorderColor            #6A584B
  skinparam SequenceParticipantBackgroundColor  #F3EFEB/CCC9C5
  skinparam SequenceParticipantBorderColor      #6A584B
  skinparam SequenceLifeLineBackgroundColor     #CCC9C5/F3EFEB
  skinparam SequenceLifeLineBorderColor         #6A584B
  skinparam SequenceArrowColor                  #6A584B
  skinparam SequenceBorderColor                 #6A584B
  skinparam SequenceFontSize                    11

  hide footbox

  box "User application" #F3EDF7
    participant "Main" as U
    participant "Event detector" as E
    participant "Event handler"  as H
  end box

  participant Propagator

  activate U
  U -> Propagator : propagate
    activate Propagator
    Propagator -> E : init
      activate E
      deactivate E
    Propagator -> Propagator : compute one step
      activate Propagator
      Propagator -> E : g
        activate E
        deactivate E
      deactivate Propagator
    Propagator -> Propagator : compute one step
      activate Propagator
      Propagator -> E : g
        activate E
        deactivate E
      Propagator -> E : g
        note right of E
          trying to find the exact date
          at which g sign changes
        end note
        activate E
        deactivate E
      Propagator -> E : g
        activate E
        deactivate E
      Propagator -> E : g
        activate E
        deactivate E
      Propagator -> E : eventOccurred
        activate E
        E -> H : eventOccurred
          activate H
          H --> E : action = CONTINUE
          deactivate H
        E--> Propagator : action
        deactivate E
      deactivate Propagator
    Propagator --> U : final state 
    deactivate Propagator
  deactivate U

@enduml
