' Copyright 2002-2020 CS Group
' Licensed to CS Group (CS) under one or more
' contributor license agreements.  See the NOTICE file distributed with
' this work for additional information regarding copyright ownership.
' CS licenses this file to You under the Apache License, Version 2.0
' (the "License"); you may not use this file except in compliance with
' the License.  You may obtain a copy of the License at
'
'   http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.
 
@startuml

  skinparam svek                  true
  skinparam ClassBackgroundColor  #F3EFEB/CCC9C5
  skinparam ClassArrowColor       #691616
  skinparam ClassBorderColor      #691616
  skinparam NoteBackgroundColor   #F3EFEB
  skinparam NoteBorderColor       #691616
  skinparam NoteFontColor         #691616
  skinparam ClassFontSize         11
  skinparam PackageFontSize       12

  package org.hipparchus #ECEBD8 {
      interface RandomVectorGenerator
  }

  package org.orekit #ECEBD8 {

    package propagation.events #DDEBD8 {
      interface EventsDetector
      note top
        ground visibility,
        ground at night,
        sunlit satellite,
        inter sat direct view,
        boolean combination...
      end note
    }
    package estimation.measurements #DDEBD8 {

      package generation #CEEBD8 {

        interface "MeasurementBuilder<T>" as MeasurementBuilder_T_ {
          +addModifier(estimationModifier)
          +T build(spacecraftStates)
         }

        class "...MeasurementBuilder" as XXXMeasurementBuilder
        note right
          one for each
          measurement type
        end note

        class Generator {
          +ObservableSatellite addPropagator(Propagator)
          +Propagator getPropagator(index)
          +addScheduler(Scheduler)
          +SortedSet<ObservedMeasurements> generate(startDate, endDate)
        }

        enum SignSemantic {
          +FEASIBLE_MEASUREMENT_WHEN_POSITIVE
          +FEASIBLE_MEASUREMENT_WHEN_NEGATIVE
        }
        class "EventBasedScheduler<T>" as EventBasedScheduler_T_
        class "ContinuousScheduler<T>" as ContinuousScheduler_T_

        interface "Scheduler<T>" as Scheduler_T_ {
          +SortedSet<T> generate(interpolators)
        }

        XXXMeasurementBuilder       ..|>          MeasurementBuilder_T_
        MeasurementBuilder_T_ "1" <--* Scheduler_T_
        XXXMeasurementBuilder -up-> RandomVectorGenerator
        SignSemantic "1" <--* EventBasedScheduler_T_
        Scheduler_T_ <|.left. EventBasedScheduler_T_
        ContinuousScheduler_T_ .right.|> Scheduler_T_
        Scheduler_T_ "*" <--* Generator
  
        EventBasedScheduler_T_ *-right-> "1" EventsDetector
      }

      interface "EstimationModifier<T>" as EstimationModifier_T_
      interface "ObservedMeasurement<T>" as ObservedMeasurement_T_
      class "...Measurement" as XXXMeasurement
      note bottom
        this box represents any
        measurement type
        (range, range-rate, ...)
      end note

 
      EstimationModifier_T_  "*" <-left-*      ObservedMeasurement_T_ 
      ObservedMeasurement_T_     <|..          XXXMeasurement
      XXXMeasurementBuilder       -->          XXXMeasurement
      EstimationModifier_T_ "*" <--* XXXMeasurementBuilder 

    }


    package propagation #DDEBD8 {
    interface Propagator
      class PropagatorsParallelizer {
        propagate()
      }
      Generator --> PropagatorsParallelizer
      Generator *--> "*" Propagator
      Propagator <-left- PropagatorsParallelizer
    }

    package time #DDEBD8 {
        class FixedStepSelector
        class BurstSelector
        interface DatesSelector {
          +selectDates(interval)
        }


        FixedStepSelector --|> DatesSelector
        BurstSelector --|> DatesSelector
        Scheduler_T_ *--> "1" DatesSelector
    }

  }

  package mission.specific #C4D2C5 {
    class "CustomScheduler<T>" as CustomScheduler_T_ #D5E0D5/E2EBE2
    Scheduler_T_ <|.up. CustomScheduler_T_
  }

@enduml
