' Copyright 2002-2016 CS Systèmes d'Information
' Licensed to CS Systèmes d'Information (CS) under one or more
' contributor license agreements.  See the NOTICE file distributed with
' this work for additional information regarding copyright ownership.
' CS licenses this file to You under the Apache License, Version 2.0
' (the "License"); you may not use this file except in compliance with
' the License.  You may obtain a copy of the License at
'
'   http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.
 
@startuml

  skinparam svek                  true
  skinparam ClassBackgroundColor  #F3EFEB/CCC9C5
  skinparam ClassArrowColor       #691616
  skinparam ClassBorderColor      #691616
  skinparam NoteBackgroundColor   #F3EFEB
  skinparam NoteBorderColor       #691616
  skinparam NoteFontColor         #691616
  skinparam ClassFontSize         11
  skinparam PackageFontSize       12

  package org.hipparchus #ECEBD8 {

          interface LeastSquaresProblem

  }

  package org.orekit #ECEBD8 {

    package estimation #DDEBD8 {

        package measurements #CEEBD8 {
            class EstimatedMeasurement
            interface ObservedMeasurement {
              +estimate(state)
            }
             ObservedMeasurement --> EstimatedMeasurement
        }
        package leastsquares #CEEBD8 {

            class MeasurementHandler

          class ODProblem
           class BatchLSEstimator {
              +addMeasurement(measurement)
              +getOrbitalParametersDrivers()
              +getPropagatorsParametersDrivers()
              +getMeasurementsParametersDrivers()
              +setObserver(observer)
              +estimate()
           }

            ODProblem *--> MeasurementHandler

          BatchLSEstimator *-right-> ODProblem
          LeastSquaresProblem <|.. ODProblem
          ODProblem --> EstimatedMeasurement
           MeasurementHandler o--> ObservedMeasurement
        }

    package propagation #DDEBD8 {
        interface Propagator
            MeasurementHandler <-- Propagator : triggers
            Propagator <-- ODProblem : run
    }

    }

  }

@enduml
