/* Copyright 2022-2025 Thales Alenia Space
 * Licensed to CS GROUP (CS) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * CS licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.orekit.orbits;

import org.orekit.frames.Frame;
import org.orekit.time.AbsoluteDate;
import org.orekit.utils.ParameterDriversList;

/** Factory for orbital parameters.
 * @param <P> type of the orbital parameters
 * @since 14.0
 */
public interface OrbitalParameterFactory<P extends OrbitalParameters> extends Cloneable {

    /** Get the drivers for orbital parameters.
     * <p>
     * There are always exactly 6 drivers for orbital parameters
     * that correspond to Keplerian motion. Some orbital
     * parameters have additional drivers for non-Keplerian motion
     * (TLE has a M2 parameter, GNSS orbital elements have Δa, iDot…)
     * These additional drivers are <em>not</em> included here, they
     * are provided by {@link #getNonKeplerianParametersDrivers()}.
     * </p>
     * @return drivers for orbital parameters
     */
    ParameterDriversList getOrbitalParametersDrivers();

    /** Get the drivers for additional drivers for non-Keplerian motion.
     * @return drivers for non-Keplerian motion
     */
    ParameterDriversList getNonKeplerianParametersDrivers();

    /** Get the frame in which the orbit is propagated.
     * @return frame in which the orbit is propagated
     */
    Frame getFrame();

    /** Set the frame in which the orbit is propagated.
     * @param frame frame in which the orbit is propagated
     */
    void setFrame(Frame frame);

    /** Get the position angle type to use.
     * @return position angle type to use
     */
    PositionAngleType getPositionAngleType();

    /** Set the position angle type to use.
     * @param positionAngleType position angle type to use
     */
    void setPositionAngleType(PositionAngleType positionAngleType);

    /** Get the date of the orbital parameters.
     * @return date of the orbital parameters
     */
    AbsoluteDate getDate();

    /** Set the date of the orbital parameters.
     * @param date date of the orbital parameters
     */
    void setDate(AbsoluteDate date);

    /** Get the central attraction coefficient (µ - m³/s²) value.
     * @return the central attraction coefficient (µ - m³/s²) value
     */
    double getMu();

    /** Set the central attraction coefficient (µ - m³/s²) value.
     * @param mu the central attraction coefficient (µ - m³/s²) value
     */
    void setMu(double mu);

    /** Reset the drivers to match specified orbit.
     * <p>
     * All of {@link #getDate() date}, {@link #getMu() mu}, and
     * {@link #getOrbitalParametersDrivers() drivers values}
     * will be reset, but neither the frame nor the type of orbital
     * parameters generated by {@link #createFromDrivers()} will be reset.
     * </p>
     * <p>
     * The specified orbit does not need to match the type of orbital
     * parameters managed by the factory. Conversion will be applied
     * if needed.
     * </p>
     * @param orbit orbit to be matched
     */
    void reset(Orbit orbit);

    /** Create orbital parameters from current drivers values.
     * @return created orbital parameters
     */
    P createFromDrivers();

}
